[package]
name = "ckb-merkle-mountain-range"
version = "0.3.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"
description = "A generalized merkle mountain range implementation"
repository = "https://github.com/nervosnetwork/merkle-mountain-range"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]

[features]
default = ["std"]
std = []

[dependencies]
cfg-if = "0.1"
wasm-bindgen = "0.2.63"
hex = "0.4.2"
sp-core = { version = "2.0"}
sp-runtime = { version = "2.0"}
serde_json = "1.0"

[dev-dependencies]
faster-hex = "0.3"
criterion = "0.3"
rand = "0.6"
proptest = "0.9.4"
lazy_static = "1.3.0"
bytes = "0.4"
blake2b-rs = "0.1.4"
array-bytes = "0.2.0"

[[bench]]
name = "mmr_benchmark"
harness = false

[[bench]]
name = "helper_benchmark"
harness = false

[lib]
crate-type = ["cdylib", "rlib"]